<?php
/**
 * Plugin Name: Flashcards Block
 * Description: Notebook-style flashcards with CSV import.
 * Author: Tino / SetupMyHotel
 * Version: 1.0.1
 */

defined( 'ABSPATH' ) || exit;

/**
 * Render callback – used on the front-end.
 *
 * $attributes['cards'] is the array of { q, a } objects saved by the block.
 * $content is the HTML generated by the JS save() function (the current UI).
 *
 * We simply output the existing content, then append an SEO-only section that
 * lists all questions and answers as real HTML so search engines can index them.
 */
function smh_flashcards_render_block( $attributes, $content ) {

    // If there are no cards or it's not the expected structure, just return the content.
    if ( empty( $attributes['cards'] ) || ! is_array( $attributes['cards'] ) ) {
        return $content;
    }

    $cards = $attributes['cards'];

    ob_start();

    // 1) Existing block HTML (what JS save() generated)
    echo $content;

    // 2) SEO-friendly HTML output (visually hidden via CSS)
    ?>
    <div class="flashcard-seo-content">
        <?php foreach ( $cards as $card ) :

            $question = isset( $card['q'] ) ? trim( wp_strip_all_tags( $card['q'] ) ) : '';
            $answer   = isset( $card['a'] ) ? trim( wp_strip_all_tags( $card['a'] ) ) : '';

            if ( $question === '' && $answer === '' ) {
                continue;
            }
            ?>
            <div class="flashcard-seo-item">
                <?php if ( $question !== '' ) : ?>
                    <h3 class="flashcard-seo-question"><?php echo esc_html( $question ); ?></h3>
                <?php endif; ?>

                <?php if ( $answer !== '' ) : ?>
                    <p class="flashcard-seo-answer"><?php echo esc_html( $answer ); ?></p>
                <?php endif; ?>
            </div>
        <?php endforeach; ?>
    </div>
    <?php

    return ob_get_clean();
}

/**
 * Register block + scripts/styles.
 */
function smh_flashcards_block_register() {

    // Editor script (block UI + CSV import)
    wp_register_script(
        'smh-flashcards-editor',
        plugins_url( 'editor.js', __FILE__ ),
        array( 'wp-blocks', 'wp-element', 'wp-block-editor', 'wp-components', 'wp-i18n' ),
        filemtime( __DIR__ . '/editor.js' )
    );

    // Front + editor styles
    wp_register_style(
        'smh-flashcards-style',
        plugins_url( 'style.css', __FILE__ ),
        array(),
        filemtime( __DIR__ . '/style.css' )
    );

    // Front-end behaviour (flip, next, fullscreen)
    wp_register_script(
        'smh-flashcards-view',
        plugins_url( 'view.js', __FILE__ ),
        array(),
        filemtime( __DIR__ . '/view.js' ),
        true
    );

    register_block_type(
        __DIR__,
        array(
            'editor_script'   => 'smh-flashcards-editor',
            'style'           => 'smh-flashcards-style',
            'view_script'     => 'smh-flashcards-view',
            'render_callback' => 'smh_flashcards_render_block',
        )
    );
}
add_action( 'init', 'smh_flashcards_block_register' );
